### ISSUE TITLE
cutadapt not found!. Required: cutadapt >=2.6

### ISSUE THREAD

**Issue by cf-Rachel** [mhalushka/miRge3.0#43]
Hi，
 I installed miRge3.0 using conda, however, each time I run the program, I always get the error 'cutadapt not found!. Required: cutadapt >=2.6'. I have re-isntalled cutadpt 2.10 through conda (when I type 'cutadapt --version', I get '2.10', is that correct?)
Thanks a lot!

Rachel

**Comment by arunhpatil** [comment]
Hi @cf-Rachel ,

This pattern is new and I wonder if cutadapt is installed in the /bin directory of conda, consider the following cases:
1) Here I created and used an environment `mirge38 `
(mirge38) arun@DESKTOP-H231NS7:~$ which cutadapt
/home/arun/miniconda3/envs/mirge38/bin/cutadapt
2) Here it is the base environment 
(base) arun@DESKTOP-H231NS7:~$ which cutadapt
/home/arun/miniconda3/bin/cutadapt

In both cases, you can see that the absolute path for cutadapt is in bin folder of miniconda3. What is the output when you type `which cutadapt`? 

I believe that the issue is with path of cutadapt. One way to resolve this issue would be to create an environment and install mirge3.0 as shown below
conda create -n mirge38 python=3.8
conda activate mirge38
conda install -c bioconda mirge3

Also, what is the version of Python installed? 

Let me know if this works. 

Thank you,
Arun.
