### ISSUE TITLE
Annotation for miRNAs

### ISSUE THREAD

**Issue by John-Drake** [mhalushka/miRge3.0#52]
Can mirge3 output an annotation file (chromosome, start position, end position) for all miRNAs detected? Can mirge3 output the canonical mature miRNA?

I've created a script that examines the human library, but I am concerned about errors. This is important as I will attempt to use the BAM files to examine mismatches. 

Examples of concern:
- 'hsa-miR-6718-3p' is outputted in the miR.Counts.csv file. However, only 'hsa-mir-6718' is found in human_miRBase.gff3 and it's a primary transcript (not mature miRNA). 'hsa-miR-6718-5p' does have a mature miRNA entry in human_miRBase.gff3. 
- 'hsa-miR-1973' is outputted in the miR.Counts.csv file. However, it doesn't seem to be listed in human_miRBase.gff3 or human_MirGeneDB.gff3. Thus, I am confused exactly where that entry is recorded in the human library. 
- The annotation syntax between MiRBase and MirGene is different (e.g. hsa-miR versus Hsa-Mir). However, the final output of mirge3 appears to follow MiRBase syntax. 
- Lastly, there are numerous merged miRNA (e.g. hsa-miR-192-5p/215-5p).

**Comment by arunhpatil** [comment]
Hi @John-Drake, 

I have tried to cover all your questions in the form they were presented and in a simple way. 

If you want the genomic coordinates, I have added them in the header of the FASTA file for each miRNAs. You could fetch and parse the header information to derive annotations as per your description. The example is shown below:
```
>hsa-let-7a-5p chr9 segs:1-30 cds:+:94175960-94175989
GATGAGGTAGTAGGTTGTATAGTTTTAGGG
>hsa-let-7a-3p chr9 segs:1-29 cds:+:94176011-94176039
AACTATACAATCTACTGTCTTTCCTAACG
```
To fetch this information, you can access the files here at path miRge3_Lib/human/index.Libs and use the following command:
`bowtie-inspect human_mirna_miRBase > miRBase_annotations.fasta`
or if you are interested in only header:
`bowtie-inspect --names human_mirna_miRBase > miRBase_annotations.txt`
example:
```
hsa-let-7a-3p chr9 segs:1-29 cds:+:94176011-94176039
hsa-let-7a-2-3p chr11 segs:1-30 cds:-:122146517-122146546
```
Please note: segs is the length of the sequence, and we have appended 2 nucleotides (nt) at 5' and 6 nt at 3' to each cannonical sequences. Besides that, cds is only a seperator and it does not mean coding sequences.  

* To answer your point one and two:
  - Where do you map the miRNAs which are in the output files but not in annotated gff3 file? 
You can find the annotations as bowtie index files (miRge3_Lib/human/index.Libs), to view this file, you can execute `bowtie-inspect miRge3_Lib/human/index.Libs/human_mirna_miRBase | less ` . This command will show you what is indexed. Not all mature miRNAs and its hairpin miRNAs present in there respective fasta FASTA file is provided in the annotated gff3 file. I unfortunately don't have an answer for that, since we obtain gff3 file from miRBase repository and they don't provide annotations for all the miRNAs in gff3. Regarding `hsa-miR-6718-3p`, they have removed this in their latest revisions and unfortunately, the database report `new` in their change log (https://mirbase.org/cgi-bin/mirna_history.pl?acc=MI0022553). I wondre if this change was recent, as there is no time stamp for individual miRNAs.  Also, please note, from the experiments reported there, 5p is dominat miRNA where as no miRNAs are reported at 3p. This should suggest that, reads from your data will have no read counts towards 3p. However, we are updating our libraries keeping all these point in view and it will be out soon.  
  - The same explanation goes for miRNA [`hsa-miR-1973`](https://mirbase.org/cgi-bin/mirna_entry.pl?acc=MI0009983)
* I have executed this SRR run SRR772403.fastq using both databases and you can see that the output has there respective names. The syntax of reporting/presenting counts and RPM is maintained the same irrespective of the databsae used. Plesae note, the annotation is not changed and it is presented as is. If you have found different output in your execution, please give us an example miRNA and we will follow up. 

This is an example counts from `MirGeneDB `
```
Hsa-Mir-10-P1a_3p*,0.0
Hsa-Mir-10-P1a_5p,44794.0
```
This is an example counts from `miRBase`
```
hsa-miR-10a-3p,0.0
hsa-miR-10a-5p,44356.0
```

* Discussion about merged miRNA can be found [here](https://github.com/mhalushka/miRge3.0/issues/34#issuecomment-1079380105)

Let us know if you need further information. 

Thank you,
Arun
