### ISSUE TITLE
Alignment behaviour query

### ISSUE THREAD

**Issue by Glfrey** [mhalushka/miRge3.0#71]
Hello again @arunhpatil ,

I'm currently working on modifying miRge3.0s alignment behaviour for my own purposes and I've noticed a routine in the code which may have the potential to output non-optimal alignment results (although it may be being handled elsewhere and I just haven't figured that out yet).  

In the function `alignPlusParse` the bowtie output, in sam format, is iterated through line by line. The sequence is looked up in the table, and the relevant column is populated with the aligned sequences reference ID (e.g. for alignment iteration 0, sequence ATAGCA aligns to miR1 (with no mismatches as none are allowed) and so column[1] corresponding to exact miRNA alignments (iteration 0) is populated with the string "miR1"). The code chunk for this is below, just so we're clear about which bit I'm talking about:

```
for srow in bwtOut.split('\n'):
        if not srow.startswith('@'):
            sam_line = srow.split('\t')
            if sam_line != ['']:
                if sam_line[2] != "*":
                    pdDataFrame.at[sam_line[0], colnames[colToAct]] = sam_line[2]
                    pdDataFrame.at[sam_line[0], colnames[0]] = 1
               
```

For exact matches this all makes sense and is clear of undesirable behaviour. 

However, when mismatches are allowed (i.e. alignment iterations 1,2,4,5,6, and 8) bowtie can report a number of equally valid alignments. For iterations 1, 4, 5, 6 and 9 no upper limit is placed on bowtie and none of the flags (e.g. -m and M) to limit the output is used. I note iteration 9 uses the `--best` flag but this doesn't limit the number of hits reports to the best of my knowledge. 

As such, should a read result in multiple hits, the same read has multiple entries in the bowtie output. As such, this results in multiple look ups of the sequence in the alignment data frame (called `pdDataFrame` in the code) and overwriting of the aligned fragments name as there (via `pdDataFrame.at[sam_line[0], colnames[colToAct]] = sam_line[2]`) as there is currently no check to see if the cell is currently populated. 

This is particularly undesirable if the `--best` flag is used as alignments are reported in decreasing quality of alignment (increasing order of mismatches) resulting in the final overwrite in the dataframe being the least optimal alignment present in the "best" set. Thus the least desirable alignment is the one reported. For iterations without the "--best" flag, the final alignment performed will be the alignment that is reported, with no reference to alignment quality (could be the best, could be the worse, it depends which sequence was checked first/last). 

Alignment iterations 2 and 3 control the number of hits reported via the combination of the `--best` and `--strata` flags, but as I describe below, there's an element of potentially undesirable behaviour stemming from these iterations too as multiple alignments are still being reported. 

I've validated this behaviour by making miRge check if the cell to be populated is already populated, and if it is, output what's in the cell and then all further matching alignments and also the final PD data frame. So far the only small RNA that falls into this trap for the sample of my data I'm working with is tRNAs. I found that indeed, it is the last of the equally valid matches that is being reported (due to overwriting) when there are actually multiple, equally valid matches to a multiple  tRNA molecules. 

Potentially, this isn't such an issue for some molecules. For example, for hairpin miRNAs, perhaps a mismatch of 1 base will not allow a read to match more than 1 molecule as all hairpin miRNAs differ by more than 1 base pair. Perhaps this is also true for snoRNAs, rRNAs and other ncRNAs. However, I think this has the potential to be problematic for isomers, where perhaps a mismatch of 2 bases, with the omission of 1 base from the 5' and 2 bases from the 3' due to bowties parameters, could cause a read to match multiple miRNAs with an equally valid alignment. In which case, it would be fair to say the classification of the reads origin is algorithmically impossible given the alignment parameters, and so it would perhaps be more correct to flag the read as a multi-mapping miRNA and output all equally valid alignments leaving it up to the user to work with, than to output the miRNA that was aligned last (as I think is currently happening due to the overwriting) given the arbitrary ordering or miRNAs in the reference files. 

Knowing that there is a set of equally valid miRNAs responsible for a reads origin is potentially critical for wet lab validation as randomly choosing one of a set that an aligner can't tell the difference between could result in failure to detect the miRNA via PCR. Providing a set of potential candidates allows the wet lab to check them all. 

Anyway, I apologise if this is something you've thought of and handled elsewhere I am of course not a knowledgeable as you to miRges' engineering. I just want to make sure this isn't something that's been missed (as happens to us all) and so could do with correction.

**Comment by arunhpatil** [comment]
Hi @Glfrey, 

I very much appreciate your efforts and suggestions. I will get back to you on your question shortly. 

Thank you,
Arun.

**Comment by arunhpatil** [comment]
Hi @Glfrey,

Below is the long answer I wrote before I came to the conclusion: 

I agree with your point of overwriting if there are multiple hits, (it is possible) I have to validate the same from the aligned intermediate sam files. I will check that and get back to you. If possible, can you provide few examples of multiple alignments for tRNAs.  To avoid this the codes to be modified as such:

From:
```
if sam_line[2] != "*":
                    pdDataFrame.at[sam_line[0], colnames[colToAct]] = sam_line[2]
                    pdDataFrame.at[sam_line[0], colnames[0]] = 1

```
To:
```
if sam_line[2] != "*" and (pdDataFrame.at[sam_line[0], colnames[0]] == 0):
                    pdDataFrame.at[sam_line[0], colnames[colToAct]] = sam_line[2]
                    pdDataFrame.at[sam_line[0], colnames[0]] = 1
```

Can you run the sample file with and with out the above code change and share the differences? 

Having all possible alignments may complicate things for users. Something to think about. I will discuss with @mhalushka and see what can be done. 

Thank you,
Arun.

------------------------------
`Old draft: `

I will try my best to answer here (and keeping users with broad backgrounds) and I am happy to have more questions. 

At first: All the identical reads are collapsed and the counts are recorded for each. If you see the mapped.csv file, you can imagine the Pandas dataframe at the backend. The second column `annotFlag` is initialized with a constant 0 (zero) for each of these collapsed reads.

[At line 55 and 56:](https://github.com/mhalushka/miRge3.0/blob/8dd2050e027231e0ecb71af8660ddbc43f993f26/mirge/libs/manifoldAlign.py#LL55C20-L56C65)  you will notice two columns are being modified here at the same time. 
```
pdDataFrame.at[sam_line[0], colnames[colToAct]] = sam_line[2]
pdDataFrame.at[sam_line[0], colnames[0]] = 1

```
The first one (line 55) determines what is the small RNA type (mature, hairpin, trna etc) and (line 56) second column records a hit, that is it will replace `annotFlag` from 0 to 1. 

As you mentioned we have several iterations of allignment. For each iterations, only reads with `annotFlag` 0 (zero) is pulled out for alignment. Our goal is to identify accurate miRNA annotations and avoid repeat elements with minor variations, thus we have stringent alignment of no mismatches and map to mature miRNAs in the first iterations and in the subsequent iterations we allow certain mismatches across all other types of RNA. There by capturing majority of the reads that are outside of miRNA boundary (false hits). Then at the last iteration we then map back to mature miRNAs with two mismatches by trimming at 5' with 1 nt and 3' with 2nt. Note when best option is used, the best alignment is picked from the best-to-worst order and we don't have phread quality values here.

The tRNA fragments has its own filtering process and strengency of annotations (not discussed here).  

You can find the following codes at [line 84](https://github.com/mhalushka/miRge3.0/blob/8dd2050e027231e0ecb71af8660ddbc43f993f26/mirge/libs/manifoldAlign.py#LL84C5-L84C141) which describes RNA types and parameters used for each type:

`indexNames = ['_mirna_', '_hairpin_', '_mature_trna', '_pre_trna', '_snorna', '_rrna', '_ncrna_others', '_mrna', '_mirna_', '_spike-in']`

`parameters = [' -n 0 -f --norc -S --threads ', ' -n 1 -f --norc -S --threads ', ' -v 1 -f -a --best --strata --norc -S --threads ', ' -v 0 -f -a --best --strata --norc -S --threads ', ' -n 1 -f --norc -S --threads ', ' -n 1 -f --norc -S --threads ', ' -n 1 -f --norc -S --threads ', ' -n 0 -f --norc -S --threads ', ' -5 1 -3 2 -v 2 -f --norc --best -S --threads ', ' -n 0 -f --norc -S --threads ']`

If I zip them both (match one to one), here are the parameters for each iterations:
```
>>> list(zip(indexNames, parameters))
[('_mirna_', ' -n 0 -f --norc -S --threads '), 
('_hairpin_', ' -n 1 -f --norc -S --threads '), 
('_mature_trna', ' -v 1 -f -a --best --strata --norc -S --threads '), 
('_pre_trna', ' -v 0 -f -a --best --strata --norc -S --threads '), 
('_snorna', ' -n 1 -f --norc -S --threads '), 
('_rrna', ' -n 1 -f --norc -S --threads '), 
('_ncrna_others', ' -n 1 -f --norc -S --threads '), 
('_mrna', ' -n 0 -f --norc -S --threads '), 
('_mirna_', ' -5 1 -3 2 -v 2 -f --norc --best -S --threads '),
('_spike-in', ' -n 0 -f --norc -S --threads ')]
>>> 
```
for example mature miRNAs [0th element]: `'_mirna_'  =>  ' -n 0 -f --norc -S --threads ' ` describes maximum number of mismatches at seed ( -n 0 ),  No reverse-complement reference alignment (--norc). This determines exact match to mature miRNAs only and so on. 

As mentioned earlier, a read with annotFlag 1 is not used for alignment in the subsequent iterations, thus number of reads used at each iterations decreases.   

Since the minimum read length by default is 16, for an isomiR: a 13 nt match with two mismatches would still have atleast 10 nt to align to two different miRNAs. The chances of it is slim to none according to my knowledge.  It may be possible to see such an event in the family of miRNAs which share identical sequence but are located on different chromosomes and report them as individual hits in mapped.csv. 

I appreciate your questions and please feel free to discuss any further questions regarding this. 

------------------------------

**Comment by Glfrey** [comment]
Hi @arunhpatil,

I can confirm that the addition to the code you produced above stopped the overwriting in the data frame and so the first alignment, of all equally scoring alignments, is reported. I still think in these instances it's probably going to be pretty important for users to be able to access all equal possible alignments for downstream validation. I can implement this myself, and will likely do so in the very near future (this week sometime) so can always do a pull request if you like? Otherwise this functionality can remain on my fork. 

As for sharing a sample of multi-aligning tRNAs, the relevant people I need to ask aren't about so I'll try and pull some public data when I get chance.

**Comment by arunhpatil** [comment]
Hi @Glfrey,

Great. If we have multiple reads with same counts but with alternate mismatches, the users may question the summation of counts for that given miRNA. Instead there must be alternative solution, like all secondary alignments should be reported to a different file altogather (secondary_matches.csv) which doesn't change the inherent reporting of counts and its conversion to RPMs. This should be fairly simple and doesn't mess up with isomiR entropy and other related default parameters. 

If the solution defined above is feasible, then I can review and accept your PR, upon confiming this with @mhalushka.  

Yes. I wouldn't need the fastq file, just the multi-mapping reads and concerned tRNAs are enough. May be have five examples (for each collapsed read). Public data is even better, then I can test on my machine too. 

Thank you,
Arun.

**Comment by Glfrey** [comment]
Hi @arunhpatil,

Yep I see your point with counts. I agree with putting all equally valid alignments into a different file for users to peruse and I'll implement that.  

I also think it would be wise to add a symbol (such as "*") to molecules with alternate equally valid alignments in the counts and RPM files (and maybe entropy?) to warn users that there exists alternate alignments to other molecules and so the observed counts may originate from either or all equally valid alignments. This might be overkill given that the secondary alignment file will be available, but my concern would be non-bioinformatic users who are simply following a smRNA differential expression pipeline may miss this file or not understand it and simply work with the counts. If the reads do truly originate from an alternate or multiple molecules their downstream validation would probably not work, or give expected results. I know that would be on them, but it's doesn't hurt to draw peoples attention to cases of ambiguity. 

I'll work with my file for testing for now as I know there's ambiguous alignments in there and then I'll test my implementations with public data. Once that's all done, I'll open a pull request and share the public dataset I used with you for your testing.

**Comment by arunhpatil** [comment]
Hi @Glfrey,

Thank you for working on this.  Your proposal is interesting and could add some additional knowledge for the user.  We are trying to gauge how often the ambiguous alignments occur in a way that are not captured by our collapsed nomenclature "Hsa-Let-7-P10_5p/7-P5_5p." It would be great to see what the data shows in this ambiguous read file from several examples and see how much of an impact this is.  Can you share that data or let us know when the code is ready to run?  As for the "*" in the counts and RPM files, we should hold off on that until we determine how much of an effect the ambiguous alignments is causing.

Thank you,
Arun.

**Comment by Glfrey** [comment]
Hi @arunhpatil,

Excellent point there, I forgot about the collapsed nomenclature. As all of my examples are for tRNAs currently I don't have any way of gauging that. The code is actually already written (I did it earlier today), I just want to run some public. data through it first to see if I can capture any other molecules than tRNAs. I should be able to get on that tomorrow and get back to you by the end of my work day.
