### ISSUE TITLE
miRbase Annotation Discrepancies

### ISSUE THREAD

**Issue by asucrer** [mhalushka/miRge3.0#75]
Hello! I've been using miRge for a while and have recently detected some discrepancies between what I expected and what I obtained, and I've been trying to understand the reasons but haven't been able to. I hope you can help me with this! 

According to your paper and other sources, there are supposed to be **2656 miRNAs in the miRbase 22 release** (which we are using), but every counts file I obtain includes **2731 miRNAs**. Trying to understand where these extra 75 miRNA came from, I checked all references and sources and detected: 

- The human library file downloaded from your sourceforge, that is exactly the same gff file currently provided by miRbase (is it not?), has **4801 entries**: 1914 corresponding to primary transcripts and 2881 to mature transcripts. Why don't any of these numbers match the expected 2656 or the given 2731? 
- When comparing the miRge output and the mirBase reference (and after splitting the IDs that you had merged together), **319 IDs were not found** in the reference... Where does the system gets these IDs from, if they are not found in the reference library?
- From these 319, I managed to find 4 in the miRbase web (but not in the downloadable files): hsa-miR-1973, hsa-miR-3713, hsa-miR-378g, hsa-miR-4456. If we are using the most recent version, how can they not be included? 
- I also detected 3 "3p" IDs where the corresponding primary and "5p" sequences were found in the DB, but not the given 3p IDs (hsa-miR-6718-3p, hsa-miR-770-3p, hsa-miR-7845-3p), and the same for 4 "5p" IDs (hsa-miR-7846-5p, hsa-miR-7849-5p, hsa-miR-7852-5p, hsa-miR-7854-5p).
- Finally, the remaining 308 IDs are pairs of "3p" and "5p" IDs. When removing the 3p/5p part, 154 matching mature miRNAs where found, but without the 3p/5p suffix. Also, 143 related primary transcript were found, but not all of them... What is the explanation for this? Where do the 3p/5p ones come from? 

During data processing do you obtain data from other sources besides the given reference library? Basically, **where is all this "extra" information coming from?** 

In my current analysis many of these transcripts had 0 reads assigned so they don't worry me much, but many others do have read counts assigned, so they are relevant in my study... How do I consider them, how do I study them further if their IDs do not exist in public DBs...?

Thank you!

**Comment by arunhpatil** [comment]
Hi @asucrer,

The discrepancies you see along with the additional (miRbase missing) 5p or 3p miRNAs were based on our previous detection of miRNA reads in the genomic loci of the annotated pri miRNAs from miRBase. These reads were part of [Toward the human cellular microRNAome](https://genome.cshlp.org/content/27/10/1769.full.pdf+html) study and since then, we have retained these passenger miRNAs as part of our miRge library.

 `A small percent (394, 0.7%) were identified in more than 50 samples. Additionally, 207 were the unassigned “passenger” 5p or 3p microRNAs from a known microRNA locus, and 15 were orthologous to a different species’microRNA (primarily primate)  (Supplemental Tables S8, S9)`

I do see the miRNAs you have mentioned missing (below) in miRBase downloadable file (the following comment), please check and let me know if I missed or didn't get your question right!
- From these 319, I managed to find 4 in the miRbase web (but not in the downloadable files): hsa-miR-1973, hsa-miR-3713, hsa-miR-378g, hsa-miR-4456. If we are using the most recent version, how can they not be included?

I hope this gives you some clarrification, please let us know if you have any further questions. 

Thank you,
Arun.

**Comment by asucrer** [comment]
Thanks for your quick reply and your explanation @arunhpatil!,

I still don't find those IDs in the file, but probably I'm checking a different version or not the file I should but not a problem! 

I can work with this :)

Thanks again!
