### ISSUE TITLE
bowtie -x index option failure

### ISSUE THREAD

**Issue by FrAoJm** [mhalushka/miRge3.0#8]
Hi! 
I am trying miRge3 on a few human samples (just 2 for testing purposes from a total of 45 fastq.gz files). 

When running it returned me the following errors:
```
miRge3.0 -s ./fastq_cat/165-EHep01-1_S25_R1_001.fastq.gz,./fastq_cat/165-EHep02-1_S26_R1_001.fastq.gz -lib /home/lab/miRge3/miRge3_Lib -on human -db mirgenedb -o output_dir -gff -nmir -trf -ai -cpu 30 -a illumina

bowtie version: 1.3.0
cutadapt version: 3.1
Samtools version: 1.10
RNAfold version: 2.4.14
Collecting and validating input files...

miRge3.0 will process 2 out of 2 input file(s).

Cutadapt finished for file 165-EHep01-1_S25_R1_001 in 21.141 second(s)
Collapsing finished for file 165-EHep01-1_S25_R1_001 in 0.6396 second(s)

Cutadapt finished for file 165-EHep02-1_S26_R1_001 in 23.9095 second(s)
Collapsing finished for file 165-EHep02-1_S26_R1_001 in 4.5516 second(s)

Matrix creation finished in 1.1645 second(s)

Data pre-processing completed in 51.8239 second(s)

Alignment in progress ...
Alignment completed in 53.947 second(s)

Summarizing and tabulating results...
Traceback (most recent call last):
  File "/home/lab/anaconda3/envs/mirge3/bin/miRge3.0", line 10, in <module>
    sys.exit(main())
  File "/home/lab/anaconda3/envs/mirge3/lib/python3.8/site-packages/mirge/__main__.py", line 103, in main
    summarize(args, workDir, ref_db, base_names, pdMapped, sampleReadCounts, trimmedReadCounts, trimmedReadCountsUnique)
  File "/home/lab/anaconda3/envs/mirge3/lib/python3.8/site-packages/mirge/libs/summary.py", line 1032, in summarize
    a2i_editing(args, cannonical_4ie, isomirs_4ie, base_names, workDir, Filtered_miRNA_Reads, mirMergedNameDic, mirDic, ref_db, seqDic, onlyCanmiRNA)
  File "/home/lab/anaconda3/envs/mirge3/lib/python3.8/site-packages/mirge/libs/mirge2_tRF_a2i.py", line 1070, in a2i_editing
    bowtie = subprocess.run(str(bwtCommand), shell=True, check=True, stdout=subprocess.PIPE, text=True, stderr=subprocess.PIPE, universal_newlines=True)
  File "/home/lab/anaconda3/envs/mirge3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bowtie  --threads 30 -x  --phred64-quals /home/lab/miRge3/miRge3_Lib/human/index.Libs/human_genome -n 1 -f -a -3 2 output_dir/miRge.2020-12-16_14-10-50/SeqToMap.fasta' returned non-zero exit status 1.
```

**I realised the bowtie command miRge3 is trying to execute is:**
```
bowtie  --threads 30 -x  --phred64-quals /home/lab/miRge3/miRge3_Lib/human/index.Libs/human_genome -n 1 -f -a -3 2 output_dir/miRge.2020-12-16_14-10-50/SeqToMap.fasta
```
After checking the sintax of bowtie in their website I saw the "-x" is to address the path to index_folder/index_basename. In the miRge3 just after the -x option appears the --phred64-quals option followed of the path to the index. 

Replacing mirge2_tRF_a2i.py lines can "fix" this issue...:
**(1058) removing  + "-x"  :**  
```       
bwtCommand = str(bwtCommand) + " --threads " + str(args.threads) 
```
**(1067) adding + "-x" :**             
```
 bwtCommand = str(bwtCommand) + " -x " + str(genome_index) + ' -n 1 -f -a -3 2 ' + str(samToMapFasta)
```

Trying to run it again give me again the same error but on lines:
```
Traceback (most recent call last):
  File "/home/lab/anaconda3/envs/mirge3/bin/miRge3.0", line 10, in <module>
    sys.exit(main())
  File "/home/lab/anaconda3/envs/mirge3/lib/python3.8/site-packages/mirge/__main__.py", line 103, in main
    summarize(args, workDir, ref_db, base_names, pdMapped, sampleReadCounts, trimmedReadCounts, trimmedReadCountsUnique)
  File "/home/lab/anaconda3/envs/mirge3/lib/python3.8/site-packages/mirge/libs/summary.py", line 1032, in summarize
    a2i_editing(args, cannonical_4ie, isomirs_4ie, base_names, workDir, Filtered_miRNA_Reads, mirMergedNameDic, mirDic, ref_db, seqDic, onlyCanmiRNA)
  File "/home/lab/anaconda3/envs/mirge3/lib/python3.8/site-packages/mirge/libs/mirge2_tRF_a2i.py", line 1302, in a2i_editing
    bowtie = subprocess.run(str(bwtCommand), shell=True, check=True, stdout=subprocess.PIPE, text=True, stderr=subprocess.PIPE, universal_newlines=True)
  File "/home/lab/anaconda3/envs/mirge3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bowtie  --threads 30 -x  --phred64-quals /home/lab/miRge3/miRge3_Lib/human/index.Libs/human_genome -n 0 -f -a -3 2 output_dir/miRge.2020-12-16_15-48-07/SeqToJudge.fasta' returned non-zero exit status 1.
```

I did the same operation than before **but with lines 1293 and 1301**. 

**After this miRge3 was able to finish with the following output:**
```
bowtie version: 1.3.0
cutadapt version: 3.1
Samtools version: 1.10
RNAfold version: 2.4.14
Collecting and validating input files...

miRge3.0 will process 2 out of 2 input file(s).

Cutadapt finished for file 165-EHep01-1_S25_R1_001 in 25.0222 second(s)
Collapsing finished for file 165-EHep01-1_S25_R1_001 in 0.727 second(s)

Cutadapt finished for file 165-EHep02-1_S26_R1_001 in 26.0285 second(s)
Collapsing finished for file 165-EHep02-1_S26_R1_001 in 6.4742 second(s)

Matrix creation finished in 1.1876 second(s)

Data pre-processing completed in 59.8659 second(s)

Alignment in progress ...
Alignment completed in 54.6129 second(s)

Summarizing and tabulating results...
The number of A-to-I editing sites is less than 10 so that no heatmap is drawn.
Summary completed in 10.8531 second(s)

Predicting novel miRNAs


Performing prediction of novel miRNAs...
Start to predict
No cluster sequences are generated and prediction is aborted.
Prediction of novel miRNAs Completed (39.17 sec)

The analysis completed in 166.7825 second(s)

```

I don't know if this way is a proper way to fixed. I would feel more confident if you can double-check this and let me know if that is correct or this implies other changes in the code. Also, if the original code is ok, could you help me to solve why it give me these errors? 

Also, I didn't check why the prediction didn't work :)

Thank you in advance and kind regards!!

**Comment by arunhpatil** [comment]
Hi @FrAoJm,

The problem you have fixed is correct, i.e., you have swapped `-x  --phred64-quals ` to this  `--phred64-quals -x`. Yes, this is an error and was not caught during our test runs. It is unusual because the phred64 format is set to 33 by default and (`--phred64-quals`) is being called in this case. We are adding a few extra features to IGV and will append this fix and make a new release soon. 

Regarding novel miRNA prediction, can you try a sample with a large size? Most likely there might not be any novel miRNA or enough reads to support that call. However, keeping in mind the above issue, I will check the codes again before we make a new release. 

Cheers,
Arun

**Comment by zyangx** [comment]
May I ask where can I found the 'mirge2_tRF_a2i.py' from the system? Just meet the same problem, I used conda and pip for installing the miRge3.0, the 'miRge3.0' can be found from "~/.local/bin", but  I cannot find the  'mirge2_tRF_a2i.py'

**Comment by arunhpatil** [comment]
@zyangx, 

If you are using conda in a particular environment name say 'mirge38', then the script can be found at the following path: `miniconda3/envs/mirge38/lib/python3.8/site-packages/mirge/libs/`. Instead, if you are using the base environment, then you can find the script at: `miniconda3/lib/python3.8/site-packages/mirge/libs/`

For pip installation, on ubuntu, you can find it at `.local/lib/python3.8/site-packages/`. Also, please share the error message you have received. I will update this on Bioconda next week.

**Comment by zyangx** [comment]
This is the error message what I got:

Summarizing and tabulating results...
Traceback (most recent call last):
  File "/home/yangzhen/.local/bin/miRge3.0", line 8, in <module>
    sys.exit(main())
  File "/home/yangzhen/.local/lib/python3.8/site-packages/mirge/__main__.py", line 103, in main
    summarize(args, workDir, ref_db, base_names, pdMapped, sampleReadCounts, trimmedReadCounts, trimmedReadCountsUnique)
  File "/home/yangzhen/.local/lib/python3.8/site-packages/mirge/libs/summary.py", line 1032, in summarize
    a2i_editing(args, cannonical_4ie, isomirs_4ie, base_names, workDir, Filtered_miRNA_Reads, mirMergedNameDic, mirDic, ref_db, seqDic, onlyCanmiRNA)
  File "/home/yangzhen/.local/lib/python3.8/site-packages/mirge/libs/mirge2_tRF_a2i.py", line 1070, in a2i_editing
    bowtie = subprocess.run(str(bwtCommand), shell=True, check=True, stdout=subprocess.PIPE, text=True, stderr=subprocess.PIPE, universal_newlines=True)
  File "/home/yangzhen/Software/miniconda2/envs/py38/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bowtie  --threads 12 -x  --phred64-quals /miRNA-seq_pipeline/miRge/miRge3_Lib/human/index.Libs/human_genome -n 1 -f -a -3 2 output_dir/miRge.2021-04-16_23-47-17/SeqToMap.fasta' returned non-zero exit status 1.

But I'm sorry I still can not find the script from .local/lib/python3.8/site-packages/. there are two folders called "mirge3-0.0.7.dist-info" and 'mirge', but no such a script was found from them. The method I used to install miRge 3.0 is to create an python3.8 environment by using conda, but I can not install 3.0 by using "conda install -c bioconda mirge3", instead, I uesd 'python3.8 -m pip install --user mirge3' in this conda environment. Then miRge3.0 works but stucks at this bowtie step. Sorry not very familiar with python, It is not necessary for me to use 2.0 as long as 3.0 works, but now I  get neigher of them run.

**Comment by zyangx** [comment]
Oh, sorry, it seems out there, let me try

**Comment by zyangx** [comment]
Update:

Now I can run miRg3.0 for small sample size data, but still get stuck when large sample size used. It seems due to the Memory limit, error report like:

##

Predicting novel miRNAs


Performing prediction of novel miRNAs...
Start to predict
Traceback (most recent call last):
  File "/home/yangzhen/.local/bin/miRge3.0", line 8, in <module>
    sys.exit(main())
  File "/home/yangzhen/.local/lib/python3.8/site-packages/mirge/__main__.py", line 140, in main
    predict_nmir(args, workDir, ref_db, base_names, pdUnmapped)
  File "/home/yangzhen/.local/lib/python3.8/site-packages/mirge/libs/novel_mir.py", line 332, in predict_nmir
    convert2Fasta(pdUnmapped, infile, minLength, maxLength, countCutoff, outputdir2, species, speciesNameDic, base_names,rawReadCounts,filteredReadCounts)
  File "/home/yangzhen/.local/lib/python3.8/site-packages/mirge/libs/novel_mir.py", line 52, in convert2Fasta
    unmapList = unmap.reset_index().values.tolist()
  File "/home/yangzhen/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5486, in values
    self._consolidate_inplace()
  File "/home/yangzhen/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5347, in _consolidate_inplace
    self._protect_consolidate(f)
  File "/home/yangzhen/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5336, in _protect_consolidate
    result = f()
  File "/home/yangzhen/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5345, in f
    self._data = self._data.consolidate()
  File "/home/yangzhen/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 940, in consolidate
    bm._consolidate_inplace()
  File "/home/yangzhen/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 945, in _consolidate_inplace
    self.blocks = tuple(_consolidate(self.blocks))
  File "/home/yangzhen/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1886, in _consolidate
    merged_blocks = _merge_blocks(
  File "/home/yangzhen/.local/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 3099, in _merge_blocks
    new_values = np.vstack([b.values for b in blocks])
  File "<__array_function__ internals>", line 5, in vstack
  File "/home/yangzhen/Software/miniconda2/envs/py38/lib/python3.8/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
numpy.core._exceptions.MemoryError: Unable to allocate 12.0 GiB for an array with shape (66, 24368923) and data type int64

**Comment by arunhpatil** [comment]
@zyangx,

Hi, thank you for the error report. Assuming your computer has sufficient memory, I believe it is related to overcommitting memory issues: I found some similar issues and solutions in this regard. `Please use these solutions with caution ` .  

Basic information on overcommit handling modes [here](https://www.kernel.org/doc/Documentation/vm/overcommit-accounting);
Solution for issue 1 [here](https://stackoverflow.com/questions/57507832/unable-to-allocate-array-with-shape-and-data-type)
Solution for issue 2 [here](https://stackoverflow.com/questions/58705843/unable-to-allocate-array-with-shape-1482535-67826-and-data-type-int64?noredirect=1&lq=1)

I hope this helps.
