### ISSUE TITLE
db versions

### ISSUE THREAD

**Issue by knokknok** [mhalushka/miRge3.0#83]
Which versions of miRBase and miRGeneDB where used to create the provided libraries (https://sourceforge.net/projects/mirge3/files/miRge3_Lib)?

**Comment by arunhpatil** [comment]
Hi @knokknok 

We have used the current version of both miRBase (Release 22) and miRGeneDB (2.1). 

Thank you,
Arun.

**Comment by knokknok** [comment]
Hi again,
I am surprised to see "Hsa-Mir-10-P1a" in my results...
Are you sure v2.0 of miRGeneDB wasn't used?
If so would it be possible to update with v2.1?
Thanks!

**Comment by arunhpatil** [comment]
Hi @knokknok,

You are right about it. I will check and update with v2.1 soon. 

Thank you,
Arun.

**Comment by knokknok** [comment]
Thanks!
Would you have an ETA?

**Comment by arunhpatil** [comment]
Hi @knokknok, 

I will have to get back to you on this one. Also, it looks like MirGeneDB 2.2 will be released soon. We will contact the authors and get an update. ETA for 2.1 can be around Monday (if everything goes smoothly). 

Thank you,
Arun.

**Comment by arunhpatil** [comment]
Hi @knokknok, 

I have uploaded the MirGeneDB 2.1 file and you can download it as follows:

`wget -O human.tar.gz "https://sourceforge.net/projects/mirge3/files/miRge3_Lib/MirGeneDB/v2.1/human.tar.gz/download" 
`

PS: You may notice that, we have picked only miRNAs with V1 extensions off the other variations of miRNAs with V2, V3 and V4 etc, this is because they are slight adjustments around the V1 canonical miRNA and we capture more nucleotides around V1, thus only v1's are retained in the database. 

Thank you,
Arun.

**Comment by knokknok** [comment]
Thanks a lot!
